export default {
    "login": "Adeniyi085",
    "id": 35613034,
    "node_id": "MDQ6VXNlcjM1NjEzMDM0",
    "avatar_url": "https://avatars3.githubusercontent.com/u/35613034?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Adeniyi085",
    "html_url": "https://github.com/Adeniyi085",
    "followers_url": "https://api.github.com/users/Adeniyi085/followers",
    "following_url": "https://api.github.com/users/Adeniyi085/following{/other_user}",
    "gists_url": "https://api.github.com/users/Adeniyi085/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Adeniyi085/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Adeniyi085/subscriptions",
    "organizations_url": "https://api.github.com/users/Adeniyi085/orgs",
    "repos_url": "https://api.github.com/users/Adeniyi085/repos",
    "events_url": "https://api.github.com/users/Adeniyi085/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Adeniyi085/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Adegelu Oluwatobi Adeniyi ",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "A graduate of Computer Science and a full stack web developer. I am proficient using Html5, JavaScript, CSS, Nodejs, React, Mongodb",
    "twitter_username": null,
    "public_repos": 26,
    "public_gists": 0,
    "followers": 0,
    "following": 1,
    "created_at": "2018-01-19T21:07:04Z",
    "updated_at": "2020-11-26T21:40:58Z"
  }
